"""Pydantic models describing the input files and the produced results.

The input models are deliberately tolerant: unknown keys are ignored so that
a richer definition file (for instance one with a description on every
parameter) still loads. The output model is strict, because its shape is
imposed by the subject.
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

#: Parameter types the constrained decoder knows how to generate.
SUPPORTED_TYPES = ("string", "number", "integer", "boolean")


class FunctionParameter(BaseModel):
    """Declared type of one function argument.

    Attributes:
        type: One of :data:`SUPPORTED_TYPES`.
    """

    model_config = ConfigDict(extra="ignore")

    type: str

    @field_validator("type")
    @classmethod
    def check_type(cls, value: str) -> str:
        """Refuse a type the decoder cannot constrain.

        Args:
            value: Declared type name.

        Returns:
            The same value when it is supported.

        Raises:
            ValueError: If the type is unknown.
        """
        if value not in SUPPORTED_TYPES:
            supported = ", ".join(SUPPORTED_TYPES)
            raise ValueError(
                f"unsupported parameter type {value!r} "
                f"(supported: {supported})"
            )
        return value


class ReturnDefinition(BaseModel):
    """Declared return type of a function.

    The return type is never generated, so it is only required to be a
    string.

    Attributes:
        type: Declared return type name.
    """

    model_config = ConfigDict(extra="ignore")

    type: str


class FunctionDefinition(BaseModel):
    """One callable function from ``functions_definition.json``.

    Attributes:
        name: Function name, generated by the model under constraint.
        description: Natural language description shown to the model.
        parameters: Argument name to declared type, in file order.
        returns: Declared return type.
    """

    model_config = ConfigDict(extra="ignore")

    name: str
    description: str = ""
    parameters: dict[str, FunctionParameter] = Field(default_factory=dict)
    returns: ReturnDefinition | None = None

    @field_validator("name")
    @classmethod
    def check_name(cls, value: str) -> str:
        """Refuse a name that could not be written inside a JSON string.

        Args:
            value: Function name.

        Returns:
            The same value when it is acceptable.

        Raises:
            ValueError: If the name is empty or contains a quote, a
                backslash or a control character.
        """
        if value == "":
            raise ValueError("function name must not be empty")
        for char in value:
            if char in '"\\' or ord(char) < 0x20:
                raise ValueError(f"unsupported character in name {value!r}")
        return value


class PromptItem(BaseModel):
    """One natural language request from ``function_calling_tests.json``.

    Attributes:
        prompt: The request text.
    """

    model_config = ConfigDict(extra="ignore")

    prompt: str


class FunctionCallResult(BaseModel):
    """One entry of the output file.

    Attributes:
        prompt: The original request.
        name: The chosen function.
        parameters: Argument name to generated value.
    """

    model_config = ConfigDict(extra="forbid")

    prompt: str
    name: str
    parameters: dict[str, Any]
